const enum FormGroupEditionActions {
	ADD_USER = 'ADD_USER',
	REMOVE_USER = 'REMOVE_USER',
	UPDATE_USERS = 'UPDATE_USERS',
	UPDATE_GROUP_NAME = 'UPDATE_GROUP_NAME',
	UPDATE_DATA = 'UPDATE_DATA',
	UPDATE_DUE_DATE = 'UPDATE_DUE_DATE',
};

export default FormGroupEditionActions;